// ============================================
// PORTFOLIO — works-data.js
// Edit this file to add/remove/update works
// ============================================

const WORKS = [
  {
    id: 'noise-field',
    num: '01',
    title: 'Noise Field',
    year: '2025',
    category: 'Generative Art',
    role: 'Creative Developer',
    tools: 'p5.js, Canvas API',
    status: 'Personal Project',
    desc: 'A generative art series built with p5.js exploring Perlin noise, flow fields, and emergent visual patterns. Each piece is procedurally generated and unique on every run.',
    img: '',       // → put your image path here e.g. 'img/noise-field.jpg'
    link: '',      // → optional external link
  },
  {
    id: 'type-lab',
    num: '02',
    title: 'Type Lab',
    year: '2025',
    category: 'Typography',
    role: 'Designer & Developer',
    tools: 'HTML, CSS, JavaScript',
    status: 'Academic Project',
    desc: 'An experimental typography project exploring how letterforms can animate, distort, and evolve. Each experiment treats type as a living, kinetic object.',
    img: '',
    link: '',
  },
  {
    id: 'motion-study',
    num: '03',
    title: 'Motion Study',
    year: '2025',
    category: 'Motion Design',
    role: 'Front-End Developer',
    tools: 'CSS Animation, GSAP',
    status: 'Ongoing',
    desc: 'A collection of CSS and JavaScript animation experiments focused on easing, timing, and micro-interactions. Each study isolates a single motion principle.',
    img: '',
    link: '',
  },
  {
    id: 'ui-ux-study',
    num: '04',
    title: 'UI / UX Study',
    year: '2025',
    category: 'Interface Design',
    role: 'UI Designer & Researcher',
    tools: 'Figma, FigJam',
    status: 'Completed',
    desc: 'A case study exploring information architecture and visual hierarchy to improve digital product usability. Involved user research, wireframing, and high-fidelity prototyping.',
    img: '',
    link: '',
  },
  {
    id: 'web-experiment',
    num: '05',
    title: 'Web Experiment',
    year: '2024',
    category: 'Web Development',
    role: 'Front-End Developer',
    tools: 'HTML, CSS, Vanilla JS',
    status: 'Ongoing',
    desc: 'A sandbox of unusual web interactions: magnetic cursors, scroll-driven reveals, text scramble effects, and layout transitions that push the raw limits of the web platform.',
    img: '',
    link: '',
  },
  {
    id: 'creative-code',
    num: '06',
    title: 'Creative Code',
    year: '2024',
    category: 'Creative Coding',
    role: 'Creative Developer',
    tools: 'JavaScript, p5.js, Canvas API',
    status: 'Ongoing',
    desc: 'Generative art sketches exploring how mathematics and code intersect in visual expression. Every sketch is written from scratch, treating the browser as a blank sketchbook.',
    img: '',
    link: '',
  },
];
